// <auto-generated />
using System;
using BooksShop.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BooksShop.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BooksShop.DAL.Entities.Binding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bindingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bindings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            bindingType = "Hard"
                        },
                        new
                        {
                            Id = 2,
                            bindingType = "Soft"
                        });
                });

            modelBuilder.Entity("BooksShop.DAL.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            category = "Horror"
                        },
                        new
                        {
                            Id = 2,
                            category = "Fantasy"
                        },
                        new
                        {
                            Id = 3,
                            category = "Detective"
                        });
                });

            modelBuilder.Entity("BooksShop.DAL.Entities.MainPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MainPhotos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            path = "shinig.jpg"
                        },
                        new
                        {
                            Id = 2,
                            path = "drSleep.jpg"
                        },
                        new
                        {
                            Id = 3,
                            path = "Psycho.jpg"
                        },
                        new
                        {
                            Id = 4,
                            path = "PetSematary.jpg"
                        },
                        new
                        {
                            Id = 5,
                            path = "It.jpg"
                        },
                        new
                        {
                            Id = 6,
                            path = "joyland.jpg"
                        },
                        new
                        {
                            Id = 7,
                            path = "joyland.jpg"
                        },
                        new
                        {
                            Id = 8,
                            path = "outsider.jpg"
                        },
                        new
                        {
                            Id = 9,
                            path = "outsider.jpg"
                        },
                        new
                        {
                            Id = 10,
                            path = "joyland.jpg"
                        },
                        new
                        {
                            Id = 11,
                            path = "lotr.jpg"
                        },
                        new
                        {
                            Id = 12,
                            path = "hpp.jpg"
                        },
                        new
                        {
                            Id = 13,
                            path = "hpch.jpg"
                        },
                        new
                        {
                            Id = 14,
                            path = "hppa.jpg"
                        },
                        new
                        {
                            Id = 15,
                            path = "hpgf.jpg"
                        },
                        new
                        {
                            Id = 16,
                            path = "hpop.jpg"
                        },
                        new
                        {
                            Id = 17,
                            path = "hphbp.jpg"
                        },
                        new
                        {
                            Id = 18,
                            path = "hpdh.jpg"
                        });
                });

            modelBuilder.Entity("BooksShop.DAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("bindingId")
                        .HasColumnType("int");

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("mainPhotoId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("numberPages")
                        .HasMaxLength(7)
                        .HasColumnType("int");

                    b.Property<float>("price")
                        .HasMaxLength(6)
                        .HasColumnType("real");

                    b.Property<int>("value")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("bindingId");

                    b.HasIndex("categoryId");

                    b.HasIndex("mainPhotoId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            bindingId = 1,
                            categoryId = 1,
                            description = "The Shining is a 1977 horror novel by American author Stephen King. It is King's third published novel and first hardback bestseller; its success firmly established King as a preeminent author in the horror genre. The setting and characters are influenced by King's personal experiences, including both his visit to The Stanley Hotel in 1974 and his struggle with alcoholism. The novel was adapted into a 1980 film of the same name. The book was followed by a sequel, Doctor Sleep, published in 2013, which was adapted into a film of the same name.",
                            mainPhotoId = 1,
                            name = "Shining",
                            numberPages = 447,
                            price = 380f,
                            value = 100
                        },
                        new
                        {
                            Id = 2,
                            bindingId = 1,
                            categoryId = 1,
                            description = "Doctor Sleep is a 2013 horror novel by American writer Stephen King and the sequel to his 1977 novel The Shining. The book reached the first position on The New York Times Best Seller list for print and ebook fiction (combined), hardcover fiction, and ebook fiction. Doctor Sleep won the 2013 Bram Stoker Award for Best Novel.",
                            mainPhotoId = 2,
                            name = "Doctor Sleep",
                            numberPages = 564,
                            price = 420f,
                            value = 100
                        },
                        new
                        {
                            Id = 3,
                            bindingId = 2,
                            categoryId = 1,
                            description = "Psycho is a 1959 horror novel by American writer Robert Bloch. The novel tells the story of Norman Bates, a caretaker at an isolated motel who struggles under his domineering mother and becomes embroiled in a series of murders. The novel is considered Bloch's most enduring work and one of the most influential horror books of the 20th century.",
                            mainPhotoId = 3,
                            name = "Psycho",
                            numberPages = 185,
                            price = 320f,
                            value = 50
                        },
                        new
                        {
                            Id = 4,
                            bindingId = 1,
                            categoryId = 1,
                            description = "Pet Sematary is a 1983 horror novel by American writer Stephen King. The novel was nominated for a World Fantasy Award for Best Novel in 1986,[1] and adapted into two films: one in 1989 and another in 2019. In November 2013, PS Publishing released Pet Sematary in a limited 30th-anniversary edition.",
                            mainPhotoId = 4,
                            name = "Pet Sematary",
                            numberPages = 373,
                            price = 420f,
                            value = 50
                        },
                        new
                        {
                            Id = 5,
                            bindingId = 1,
                            categoryId = 1,
                            description = "It is a 1986 horror novel by American author Stephen King. It was his 22nd book and his 17th novel written under his own name. The story follows the experiences of seven children as they are terrorized by an evil entity that exploits the fears of its victims to disguise itself while hunting its prey. It primarily appears in the form of Pennywise the Dancing Clown to attract its preferred prey of young children.",
                            mainPhotoId = 5,
                            name = "It",
                            numberPages = 1138,
                            price = 820f,
                            value = 50
                        },
                        new
                        {
                            Id = 6,
                            bindingId = 1,
                            categoryId = 1,
                            description = "Joyland is a novel by American writer Stephen King, published in 2013 by Hard Case Crime. It is King's second book for the imprint, following The Colorado Kid (2005). The first edition was released only in paperback, with the cover art created by Robert McGinnis and Glen Orbik. A limited hardcover edition followed a week later.[1][2] The novel was nominated for the 2014 Edgar Award for Best Paperback Original",
                            mainPhotoId = 6,
                            name = "Joyland",
                            numberPages = 1138,
                            price = 820f,
                            value = 50
                        },
                        new
                        {
                            Id = 7,
                            bindingId = 2,
                            categoryId = 1,
                            description = "Joyland is a novel by American writer Stephen King, published in 2013 by Hard Case Crime. It is King's second book for the imprint, following The Colorado Kid (2005). The first edition was released only in paperback, with the cover art created by Robert McGinnis and Glen Orbik. A limited hardcover edition followed a week later.[1][2] The novel was nominated for the 2014 Edgar Award for Best Paperback Original",
                            mainPhotoId = 7,
                            name = "Joyland",
                            numberPages = 288,
                            price = 190f,
                            value = 50
                        },
                        new
                        {
                            Id = 8,
                            bindingId = 1,
                            categoryId = 1,
                            description = "The Outsider (2018) is a horror novel by the American author Stephen King. The novel was published by Scribner.",
                            mainPhotoId = 8,
                            name = "Outsider",
                            numberPages = 560,
                            price = 420f,
                            value = 50
                        },
                        new
                        {
                            Id = 9,
                            bindingId = 2,
                            categoryId = 1,
                            description = "The Outsider (2018) is a horror novel by the American author Stephen King. The novel was published by Scribner.",
                            mainPhotoId = 9,
                            name = "Outsider",
                            numberPages = 560,
                            price = 420f,
                            value = 50
                        },
                        new
                        {
                            Id = 10,
                            bindingId = 2,
                            categoryId = 1,
                            description = "Joyland is a novel by American writer Stephen King, published in 2013 by Hard Case Crime. It is King's second book for the imprint, following The Colorado Kid (2005). The first edition was released only in paperback, with the cover art created by Robert McGinnis and Glen Orbik. A limited hardcover edition followed a week later.[1][2] The novel was nominated for the 2014 Edgar Award for Best Paperback Original",
                            mainPhotoId = 10,
                            name = "Joyland",
                            numberPages = 288,
                            price = 190f,
                            value = 50
                        },
                        new
                        {
                            Id = 11,
                            bindingId = 1,
                            categoryId = 2,
                            description = "The Lord of the Rings is an epic[1] high-fantasy novel[a] by English author and scholar J. R. R. Tolkien. Set in Middle-earth, intended to be Earth at some distant time in the past, the story began as a sequel to Tolkien's 1937 children's book The Hobbit, but eventually developed into a much larger work. Written in stages between 1937 and 1949, The Lord of the Rings is one of the best-selling books ever written, with over 150 million copies sold.",
                            mainPhotoId = 11,
                            name = "The Lord of the Rings",
                            numberPages = 840,
                            price = 720f,
                            value = 50
                        },
                        new
                        {
                            Id = 12,
                            bindingId = 1,
                            categoryId = 2,
                            description = "Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school, and with the help of his friends, he faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.",
                            mainPhotoId = 12,
                            name = "Harry Potter and the Philosopher's Stone",
                            numberPages = 223,
                            price = 380f,
                            value = 100
                        },
                        new
                        {
                            Id = 13,
                            bindingId = 1,
                            categoryId = 2,
                            description = "Harry Potter and the Chamber of Secrets is a fantasy novel written by British author J. K. Rowling and the second novel in the Harry Potter series. The plot follows Harry's second year at Hogwarts School of Witchcraft and Wizardry, during which a series of messages on the walls of the school's corridors warn that the Chamber of Secrets has been opened and that the heir of Slytherin would kill all pupils who do not come from all-magical families. These threats are found after attacks that leave residents of the school petrified. Throughout the year, Harry and his friends Ron and Hermione investigate the attacks.",
                            mainPhotoId = 13,
                            name = "Harry Potter and the Chamber of Secrets",
                            numberPages = 251,
                            price = 400f,
                            value = 100
                        },
                        new
                        {
                            Id = 14,
                            bindingId = 1,
                            categoryId = 2,
                            description = "Harry Potter and the Prisoner of Azkaban is a fantasy novel written by British author J. K. Rowling and is the third in the Harry Potter series. The book follows Harry Potter, a young wizard, in his third year at Hogwarts School of Witchcraft and Wizardry. Along with friends Ronald Weasley and Hermione Granger, Harry investigates Sirius Black, an escaped prisoner from Azkaban, the wizard prison, believed to be one of Lord Voldemort's old allies.",
                            mainPhotoId = 14,
                            name = "Harry Potter and the Prisoner of Azkaban",
                            numberPages = 317,
                            price = 420f,
                            value = 100
                        },
                        new
                        {
                            Id = 15,
                            bindingId = 1,
                            categoryId = 2,
                            description = "Harry Potter and the Goblet of Fire is a fantasy novel written by British author J. K. Rowling and the fourth novel in the Harry Potter series. It follows Harry Potter, a wizard in his fourth year at Hogwarts School of Witchcraft and Wizardry, and the mystery surrounding the entry of Harry's name into the Triwizard Tournament, in which he is forced to compete.",
                            mainPhotoId = 15,
                            name = "Harry Potter and the Goblet of Fire",
                            numberPages = 636,
                            price = 440f,
                            value = 100
                        },
                        new
                        {
                            Id = 16,
                            bindingId = 1,
                            categoryId = 2,
                            description = "Harry Potter and the Order of the Phoenix is a fantasy novel written by British author J. K. Rowling and the fifth novel in the Harry Potter series. It follows Harry Potter's struggles through his fifth year at Hogwarts School of Witchcraft and Wizardry, including the surreptitious return of the antagonist Lord Voldemort, O.W.L. exams, and an obstructive Ministry of Magic. The novel was published on 21 June 2003 by Bloomsbury in the United Kingdom, Scholastic in the United States, and Raincoast in Canada. It sold five million copies in the first 24 hours of publication.[1] It is the longest book of the series.",
                            mainPhotoId = 16,
                            name = "Harry Potter and the Order of the Phoenix",
                            numberPages = 766,
                            price = 460f,
                            value = 100
                        },
                        new
                        {
                            Id = 17,
                            bindingId = 1,
                            categoryId = 2,
                            description = "Harry Potter and the Half-Blood Prince is a fantasy novel written by British author J.K. Rowling and the sixth and penultimate novel in the Harry Potter series. Set during Harry Potter's sixth year at Hogwarts, the novel explores the past of the boy wizard's nemesis, Lord Voldemort, and Harry's preparations for the final battle against Voldemort alongside his headmaster and mentor Albus Dumbledore.",
                            mainPhotoId = 17,
                            name = "Harry Potter and the Half-Blood Prince",
                            numberPages = 607,
                            price = 480f,
                            value = 100
                        },
                        new
                        {
                            Id = 18,
                            bindingId = 1,
                            categoryId = 2,
                            description = "Harry Potter and the Deathly Hallows is a fantasy novel written by British author J. K. Rowling and the seventh and final novel of the Harry Potter series. It was released on 21 July 2007 in the United Kingdom by Bloomsbury Publishing, in the United States by Scholastic, and in Canada by Raincoast Books. The novel chronicles the events directly following Harry Potter and the Half-Blood Prince (2005) and the final confrontation between the wizards Harry Potter and Lord Voldemort.",
                            mainPhotoId = 18,
                            name = "Harry Potter and the Deathly Hallows",
                            numberPages = 607,
                            price = 500f,
                            value = 100
                        });
                });

            modelBuilder.Entity("BooksShop.DAL.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "3b333929-f974-444e-a8d3-68f50a0459c0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6b4fe4ee-1ee6-4856-a30a-6d82961e0196",
                            EmailConfirmed = false,
                            FirstName = "Esmaralda",
                            LastName = "Voigt",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEJTx9VLktkPws6sjMgpDJr6rB3NHirE2XPAcGn/Au7AkMe1LeoIGJ1sDy5OhX/W1tw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d05403bc-bdf2-49b4-90a3-7337efb4a1ac",
                            TwoFactorEnabled = false,
                            UserName = "User1"
                        },
                        new
                        {
                            Id = "61dfb9e3-1c27-424a-9963-9586ca110220",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "30400dd7-f2cc-4f4e-8c0e-d458589cdb08",
                            EmailConfirmed = false,
                            FirstName = "Ostap",
                            LastName = "Bleier",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEGeVGKlN+XaW6Tisuto97avC+MSES0TkhjBLVNYs8RfQqLtKnBi5RRmU022z/BAPDw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5c6a9c30-9f10-4330-b00a-07fba3386802",
                            TwoFactorEnabled = false,
                            UserName = "User2"
                        },
                        new
                        {
                            Id = "a36b02e1-81a9-47f4-89b6-d33c4f40ed5f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fe2c5ca5-08dc-4c7c-afb8-f3c6d14f3aa0",
                            EmailConfirmed = false,
                            FirstName = "Sophia",
                            LastName = "Beringer",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEGuJKbZDDRiwEIv9bZVHLQRYCFCz+n7z5vy3Wwgzvs01A/62fKrTklLCLXW/sLwRxQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "843557ae-7268-4da5-adad-b87768e3f99e",
                            TwoFactorEnabled = false,
                            UserName = "User3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BooksShop.DAL.Entities.Product", b =>
                {
                    b.HasOne("BooksShop.DAL.Entities.Binding", "binding")
                        .WithMany("products")
                        .HasForeignKey("bindingId")
                        .HasConstraintName("FK_Products_bindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BooksShop.DAL.Entities.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("categoryId")
                        .HasConstraintName("FK_Products_categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BooksShop.DAL.Entities.MainPhoto", "mainPhoto")
                        .WithMany("product")
                        .HasForeignKey("mainPhotoId")
                        .HasConstraintName("FK_Products_mainPhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("binding");

                    b.Navigation("category");

                    b.Navigation("mainPhoto");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BooksShop.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BooksShop.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BooksShop.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BooksShop.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BooksShop.DAL.Entities.Binding", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("BooksShop.DAL.Entities.Category", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("BooksShop.DAL.Entities.MainPhoto", b =>
                {
                    b.Navigation("product");
                });
#pragma warning restore 612, 618
        }
    }
}
